export const genres = [
  { id: 1, title: "Action" },
  { id: 2, title: "Adventure" },
  { id: 3, title: "Racing" },
  { id: 4, title: "Comedy" },
  { id: 5, title: "Avant Garde" },
  { id: 6, title: "Mythology" },
  { id: 7, title: "Mystery" },
  { id: 8, title: "Drama" },
  { id: 9, title: "Ecchi" },
  { id: 10, title: "Fantasy" },
  { id: 12, title: "Hentai" },
  { id: 13, title: "Historical" },
  { id: 14, title: "Horror" },
  { id: 18, title: "Mecha" },
  { id: 21, title: "Samurai" },
  { id: 22, title: "Romance" },
  { id: 24, title: "Sci-Fi" },
  { id: 26, title: "Girls Love" },
  { id: 27, title: "Shounen" },
  { id: 30, title: "Sports" },
  { id: 36, title: "Slice of Life" },
  { id: 37, title: "Supernatural" },
  { id: 41, title: "Suspense" },
  { id: 46, title: "Award Winning" },
  { id: 47, title: "Gourmet" },
];
